project:
  type: website

website:
  favicon: assets/favicon.ico
  site-url: https://stat33b.berkeley.edu/spring-2026/
  google-analytics: G-CES9J82GLL
  sidebar:
    style: docked
    title: "STAT 33B <br><small>Spring 2026</small>"
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    tools:
      - icon: github
        href: https://github.com/berkeley-stat33b/spring-2026/
        aria-label: GitHub
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: about.qmd
        text: About
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.qmd
          - units/unit3.qmd
          - units/unit4.qmd
          - units/unit5.qmd
          - units/unit6.qmd
          - units/unit7.qmd
          - units/unit8.qmd
          - units/unit9.qmd
          - units/unit10.qmd
          - units/unit11.qmd
          - units/unit12.qmd
          - units/unit13.qmd
          - units/unit14.qmd
      - section: "Other"
        contents:
          - href: staff.qmd
            text: Staff
          - href: cheatsheets.qmd
            text: Cheatsheets
          - href: email.qmd
            text: Email
          - href: faqs.qmd
            text: FAQs
          - href: ed-netiquette.qmd
            text: "Ed Netiquette"
          - href: license.qmd
            text: License
          

format:
  html:
    theme: yeti
    fontsize: 0.9em
    css: assets/styles.css
    toc: true
